name: Deploy FastAPI to EC2 (No Docker)

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/first-fastAPI-app || git clone https://github.com/${{ github.repository }} ~/first-fastAPI-app && cd ~/first-fastAPI-app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill uvicorn || true
            nohup uvicorn main:app --host 0.0.0.0 --port 80 > log.txt 2>&1 &
