name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/first-fastAPI-app
          git pull origin main
          docker stop todo-app || true
          docker rm todo-app || true
          docker build -t fastapi-todo .
          docker run -d -p 80:80 --name todo-app fastapi-todo
